mode : local
train_batch_size : 10
valid_batch_size : 2

num_training_updates : 10000

num_hiddens : 128
num_residual_hiddens : 32
num_residual_layers : 2

embedding_dim : 64
num_embeddings : 512

commitment_cost : 0.25

decay : 0.99
learning_rate : 1e-3

use_norm : True